PLAN = "GEOGRAPHICALGRIDSYSTEMS.PLANIGN"
CLASSIC = "GEOGRAPHICALGRIDSYSTEMS.MAPS"
SE_STANDARD = "GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.STANDARD"
SE_CLASSIC = "GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.CLASSIQUE"
SE_GRAYSCALE = "GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.NIVEAUXGRIS"

DEFAULT = SE_STANDARD